// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package lock_configuration

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.MaxRetentionDays, b.ko.Spec.MaxRetentionDays) {
		delta.Add("Spec.MaxRetentionDays", a.ko.Spec.MaxRetentionDays, b.ko.Spec.MaxRetentionDays)
	} else if a.ko.Spec.MaxRetentionDays != nil && b.ko.Spec.MaxRetentionDays != nil {
		if *a.ko.Spec.MaxRetentionDays != *b.ko.Spec.MaxRetentionDays {
			delta.Add("Spec.MaxRetentionDays", a.ko.Spec.MaxRetentionDays, b.ko.Spec.MaxRetentionDays)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MinRetentionDays, b.ko.Spec.MinRetentionDays) {
		delta.Add("Spec.MinRetentionDays", a.ko.Spec.MinRetentionDays, b.ko.Spec.MinRetentionDays)
	} else if a.ko.Spec.MinRetentionDays != nil && b.ko.Spec.MinRetentionDays != nil {
		if *a.ko.Spec.MinRetentionDays != *b.ko.Spec.MinRetentionDays {
			delta.Add("Spec.MinRetentionDays", a.ko.Spec.MinRetentionDays, b.ko.Spec.MinRetentionDays)
		}
	}

	return delta
}
