// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_vault

import (
	"bytes"

	access_policy "github.com/aws-controllers-k8s/backup-controller/pkg/resource/backup_vault/access_policy"
	notifications "github.com/aws-controllers-k8s/backup-controller/pkg/resource/backup_vault/notifications"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AccessPolicy, b.ko.Spec.AccessPolicy) {
		delta.Add("Spec.AccessPolicy", a.ko.Spec.AccessPolicy, b.ko.Spec.AccessPolicy)
	} else if a.ko.Spec.AccessPolicy != nil && b.ko.Spec.AccessPolicy != nil {
		if len(access_policy.NewSpecDelta(a.ko.Spec.AccessPolicy, b.ko.Spec.AccessPolicy).Differences) > 0 {
			delta.Add("Spec.AccessPolicy", a.ko.Spec.AccessPolicy, b.ko.Spec.AccessPolicy)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN) {
		delta.Add("Spec.EncryptionKeyARN", a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN)
	} else if a.ko.Spec.EncryptionKeyARN != nil && b.ko.Spec.EncryptionKeyARN != nil {
		if *a.ko.Spec.EncryptionKeyARN != *b.ko.Spec.EncryptionKeyARN {
			delta.Add("Spec.EncryptionKeyARN", a.ko.Spec.EncryptionKeyARN, b.ko.Spec.EncryptionKeyARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.EncryptionKeyRef, b.ko.Spec.EncryptionKeyRef) {
		delta.Add("Spec.EncryptionKeyRef", a.ko.Spec.EncryptionKeyRef, b.ko.Spec.EncryptionKeyRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Notifications, b.ko.Spec.Notifications) {
		delta.Add("Spec.Notifications", a.ko.Spec.Notifications, b.ko.Spec.Notifications)
	} else if a.ko.Spec.Notifications != nil && b.ko.Spec.Notifications != nil {
		if len(notifications.NewSpecDelta(a.ko.Spec.Notifications, b.ko.Spec.Notifications).Differences) > 0 {
			delta.Add("Spec.Notifications", a.ko.Spec.Notifications, b.ko.Spec.Notifications)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
