// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_vault

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/backup"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/backup/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.BackupVault{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeBackupVaultOutput
	resp, err = rm.sdkapi.DescribeBackupVault(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeBackupVault", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "AccessDeniedException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupVaultArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupVaultArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupVaultName != nil {
		ko.Spec.Name = resp.BackupVaultName
	} else {
		ko.Spec.Name = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.EncryptionKeyArn != nil {
		ko.Spec.EncryptionKeyARN = resp.EncryptionKeyArn
	} else {
		ko.Spec.EncryptionKeyARN = nil
	}
	if resp.EncryptionKeyType != "" {
		ko.Status.EncryptionKeyType = aws.String(string(resp.EncryptionKeyType))
	} else {
		ko.Status.EncryptionKeyType = nil
	}
	if resp.LockDate != nil {
		ko.Status.LockDate = &metav1.Time{*resp.LockDate}
	} else {
		ko.Status.LockDate = nil
	}
	if resp.Locked != nil {
		ko.Status.Locked = resp.Locked
	} else {
		ko.Status.Locked = nil
	}
	if resp.MaxRetentionDays != nil {
		ko.Spec.MaxRetentionDays = resp.MaxRetentionDays
	} else {
		ko.Spec.MaxRetentionDays = nil
	}
	if resp.MinRetentionDays != nil {
		ko.Spec.MinRetentionDays = resp.MinRetentionDays
	} else {
		ko.Spec.MinRetentionDays = nil
	}
	ko.Status.NumberOfRecoveryPoints = &resp.NumberOfRecoveryPoints
	if resp.VaultType != "" {
		ko.Status.VaultType = aws.String(string(resp.VaultType))
	} else {
		ko.Status.VaultType = nil
	}

	rm.setStatusDefaults(ko)
	// DescribeBackupVault does not return tags, so we fetch them separately
	// using ListTags.
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		tagsResp, err := rm.sdkapi.ListTags(ctx, &svcsdk.ListTagsInput{
			ResourceArn: (*string)(ko.Status.ACKResourceMetadata.ARN),
		})
		rm.metrics.RecordAPICall("READ_ONE", "ListTags", err)
		if err != nil {
			return nil, err
		}
		if tagsResp.Tags != nil {
			ko.Spec.Tags = aws.StringMap(tagsResp.Tags)
		} else {
			ko.Spec.Tags = nil
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeBackupVaultInput, error) {
	res := &svcsdk.DescribeBackupVaultInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateBackupVaultOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBackupVault(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBackupVault", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupVaultArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupVaultArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupVaultName != nil {
		ko.Spec.Name = resp.BackupVaultName
	} else {
		ko.Spec.Name = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, ackrequeue.NeededAfter(nil, 0)
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBackupVaultInput, error) {
	res := &svcsdk.CreateBackupVaultInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}
	if r.ko.Spec.Tags != nil {
		res.BackupVaultTags = aws.ToStringMap(r.ko.Spec.Tags)
	}
	if r.ko.Spec.EncryptionKeyARN != nil {
		res.EncryptionKeyArn = r.ko.Spec.EncryptionKeyARN
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	ko := desired.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	var requeueNeeded bool

	if delta.DifferentAt("Spec.Policy") {
		ko, err = rm.sdkUpdatePutBackupVaultAccessPolicy(ctx, desired, ko)
		if err != nil {
			return nil, err
		}
		requeueNeeded = true
	}

	if delta.DifferentAt("Spec.ChangeableForDays") || delta.DifferentAt("Spec.MaxRetentionDays") || delta.DifferentAt("Spec.MinRetentionDays") {
		ko, err = rm.sdkUpdatePutBackupVaultLockConfiguration(ctx, desired, ko)
		if err != nil {
			return nil, err
		}
		requeueNeeded = true
	}

	if delta.DifferentAt("Spec.BackupVaultEvents") {
		ko, err = rm.sdkUpdatePutBackupVaultNotifications(ctx, desired, ko)
		if err != nil {
			return nil, err
		}
		requeueNeeded = true
	}

	if requeueNeeded {
		return &resource{ko}, ackrequeue.NeededAfter(nil, 0)
	}
	return &resource{ko}, nil
}

func (rm *resourceManager) sdkUpdatePutBackupVaultAccessPolicy(
	ctx context.Context,
	desired *resource,
	ko *svcapitypes.BackupVault,
) (*svcapitypes.BackupVault, error) {
	input, err := rm.newPutBackupVaultAccessPolicyPayload(desired)
	if err != nil {
		return ko, err
	}

	var resp *svcsdk.PutBackupVaultAccessPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.PutBackupVaultAccessPolicy(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutBackupVaultAccessPolicy", err)
	if err != nil {
		return ko, err
	}

	return ko, nil
}

func (rm *resourceManager) newPutBackupVaultAccessPolicyPayload(
	r *resource,
) (*svcsdk.PutBackupVaultAccessPolicyInput, error) {
	res := &svcsdk.PutBackupVaultAccessPolicyInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}
	if r.ko.Spec.Policy != nil {
		res.Policy = r.ko.Spec.Policy
	}

	return res, nil
}

func (rm *resourceManager) sdkUpdatePutBackupVaultLockConfiguration(
	ctx context.Context,
	desired *resource,
	ko *svcapitypes.BackupVault,
) (*svcapitypes.BackupVault, error) {
	input, err := rm.newPutBackupVaultLockConfigurationPayload(desired)
	if err != nil {
		return ko, err
	}

	var resp *svcsdk.PutBackupVaultLockConfigurationOutput
	_ = resp
	resp, err = rm.sdkapi.PutBackupVaultLockConfiguration(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutBackupVaultLockConfiguration", err)
	if err != nil {
		return ko, err
	}

	return ko, nil
}

func (rm *resourceManager) newPutBackupVaultLockConfigurationPayload(
	r *resource,
) (*svcsdk.PutBackupVaultLockConfigurationInput, error) {
	res := &svcsdk.PutBackupVaultLockConfigurationInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}
	if r.ko.Spec.ChangeableForDays != nil {
		res.ChangeableForDays = r.ko.Spec.ChangeableForDays
	}
	if r.ko.Spec.MaxRetentionDays != nil {
		res.MaxRetentionDays = r.ko.Spec.MaxRetentionDays
	}
	if r.ko.Spec.MinRetentionDays != nil {
		res.MinRetentionDays = r.ko.Spec.MinRetentionDays
	}

	return res, nil
}

func (rm *resourceManager) sdkUpdatePutBackupVaultNotifications(
	ctx context.Context,
	desired *resource,
	ko *svcapitypes.BackupVault,
) (*svcapitypes.BackupVault, error) {
	input, err := rm.newPutBackupVaultNotificationsPayload(desired)
	if err != nil {
		return ko, err
	}

	var resp *svcsdk.PutBackupVaultNotificationsOutput
	_ = resp
	resp, err = rm.sdkapi.PutBackupVaultNotifications(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "PutBackupVaultNotifications", err)
	if err != nil {
		return ko, err
	}

	return ko, nil
}

func (rm *resourceManager) newPutBackupVaultNotificationsPayload(
	r *resource,
) (*svcsdk.PutBackupVaultNotificationsInput, error) {
	res := &svcsdk.PutBackupVaultNotificationsInput{}

	if r.ko.Spec.BackupVaultEvents != nil {
		f0 := []svcsdktypes.BackupVaultEvent{}
		for _, f0iter := range r.ko.Spec.BackupVaultEvents {
			var f0elem string
			f0elem = string(*f0iter)
			f0 = append(f0, svcsdktypes.VaultEvent(f0elem))
		}
		res.BackupVaultEvents = f0
	}
	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteBackupVaultOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBackupVault(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBackupVault", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBackupVaultInput, error) {
	res := &svcsdk.DeleteBackupVaultInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.BackupVault,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"MissingParameterValueException",
		"InvalidRequestException":
		return true
	default:
		return false
	}
}
func (rm *resourceManager) sdkFindFieldGroups(
	ctx context.Context,
	r *resource,
	observed *resource,
) (*resource, error) {
	ko := observed.ko.DeepCopy()
	var err error

	ko, err = rm.sdkFindGetBackupVaultAccessPolicy(ctx, r, ko)
	if err != nil {
		return &resource{ko}, err
	}

	ko, err = rm.sdkFindGetBackupVaultNotifications(ctx, r, ko)
	if err != nil {
		return &resource{ko}, err
	}

	return &resource{ko}, nil
}

func (rm *resourceManager) sdkFindGetBackupVaultAccessPolicy(
	ctx context.Context,
	r *resource,
	ko *svcapitypes.BackupVault,
) (*svcapitypes.BackupVault, error) {
	input, err := rm.newGetBackupVaultAccessPolicyInput(r)
	if err != nil {
		return ko, err
	}

	var resp *svcsdk.GetBackupVaultAccessPolicyOutput
	_ = resp
	resp, err = rm.sdkapi.GetBackupVaultAccessPolicy(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBackupVaultAccessPolicy", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "AccessDeniedException" {
			return ko, nil
		}
		return ko, err
	}

	if resp.Policy != nil {
		ko.Spec.Policy = resp.Policy
	} else {
		ko.Spec.Policy = nil
	}

	return ko, nil
}

func (rm *resourceManager) newGetBackupVaultAccessPolicyInput(
	r *resource,
) (*svcsdk.GetBackupVaultAccessPolicyInput, error) {
	res := &svcsdk.GetBackupVaultAccessPolicyInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}

	return res, nil
}

func (rm *resourceManager) sdkFindGetBackupVaultNotifications(
	ctx context.Context,
	r *resource,
	ko *svcapitypes.BackupVault,
) (*svcapitypes.BackupVault, error) {
	input, err := rm.newGetBackupVaultNotificationsInput(r)
	if err != nil {
		return ko, err
	}

	var resp *svcsdk.GetBackupVaultNotificationsOutput
	_ = resp
	resp, err = rm.sdkapi.GetBackupVaultNotifications(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBackupVaultNotifications", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "AccessDeniedException" {
			return ko, nil
		}
		return ko, err
	}

	if resp.BackupVaultEvents != nil {
		f1 := []*string{}
		for _, f1iter := range resp.BackupVaultEvents {
			var f1elem *string
			f1elem = aws.String(string(f1iter))
			f1 = append(f1, f1elem)
		}
		ko.Spec.BackupVaultEvents = f1
	} else {
		ko.Spec.BackupVaultEvents = nil
	}

	return ko, nil
}

func (rm *resourceManager) newGetBackupVaultNotificationsInput(
	r *resource,
) (*svcsdk.GetBackupVaultNotificationsInput, error) {
	res := &svcsdk.GetBackupVaultNotificationsInput{}

	if r.ko.Spec.Name != nil {
		res.BackupVaultName = r.ko.Spec.Name
	}

	return res, nil
}
