// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_plan

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.BackupPlan, b.ko.Spec.BackupPlan) {
		delta.Add("Spec.BackupPlan", a.ko.Spec.BackupPlan, b.ko.Spec.BackupPlan)
	} else if a.ko.Spec.BackupPlan != nil && b.ko.Spec.BackupPlan != nil {
		if len(a.ko.Spec.BackupPlan.AdvancedBackupSettings) != len(b.ko.Spec.BackupPlan.AdvancedBackupSettings) {
			delta.Add("Spec.BackupPlan.AdvancedBackupSettings", a.ko.Spec.BackupPlan.AdvancedBackupSettings, b.ko.Spec.BackupPlan.AdvancedBackupSettings)
		} else if len(a.ko.Spec.BackupPlan.AdvancedBackupSettings) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupPlan.AdvancedBackupSettings, b.ko.Spec.BackupPlan.AdvancedBackupSettings) {
				delta.Add("Spec.BackupPlan.AdvancedBackupSettings", a.ko.Spec.BackupPlan.AdvancedBackupSettings, b.ko.Spec.BackupPlan.AdvancedBackupSettings)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BackupPlan.BackupPlanName, b.ko.Spec.BackupPlan.BackupPlanName) {
			delta.Add("Spec.BackupPlan.BackupPlanName", a.ko.Spec.BackupPlan.BackupPlanName, b.ko.Spec.BackupPlan.BackupPlanName)
		} else if a.ko.Spec.BackupPlan.BackupPlanName != nil && b.ko.Spec.BackupPlan.BackupPlanName != nil {
			if *a.ko.Spec.BackupPlan.BackupPlanName != *b.ko.Spec.BackupPlan.BackupPlanName {
				delta.Add("Spec.BackupPlan.BackupPlanName", a.ko.Spec.BackupPlan.BackupPlanName, b.ko.Spec.BackupPlan.BackupPlanName)
			}
		}
		if len(a.ko.Spec.BackupPlan.Rules) != len(b.ko.Spec.BackupPlan.Rules) {
			delta.Add("Spec.BackupPlan.Rules", a.ko.Spec.BackupPlan.Rules, b.ko.Spec.BackupPlan.Rules)
		} else if len(a.ko.Spec.BackupPlan.Rules) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupPlan.Rules, b.ko.Spec.BackupPlan.Rules) {
				delta.Add("Spec.BackupPlan.Rules", a.ko.Spec.BackupPlan.Rules, b.ko.Spec.BackupPlan.Rules)
			}
		}
		if len(a.ko.Spec.BackupPlan.ScanSettings) != len(b.ko.Spec.BackupPlan.ScanSettings) {
			delta.Add("Spec.BackupPlan.ScanSettings", a.ko.Spec.BackupPlan.ScanSettings, b.ko.Spec.BackupPlan.ScanSettings)
		} else if len(a.ko.Spec.BackupPlan.ScanSettings) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupPlan.ScanSettings, b.ko.Spec.BackupPlan.ScanSettings) {
				delta.Add("Spec.BackupPlan.ScanSettings", a.ko.Spec.BackupPlan.ScanSettings, b.ko.Spec.BackupPlan.ScanSettings)
			}
		}
	}

	return delta
}
