// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_plan

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	iamapitypes "github.com/aws-controllers-k8s/iam-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrt "github.com/aws-controllers-k8s/runtime/pkg/runtime"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles,verbs=get;list
// +kubebuilder:rbac:groups=iam.services.k8s.aws,resources=roles/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	for f0idx, f0iter := range ko.Spec.Rules {
		for f1idx, f1iter := range f0iter.CopyActions {
			if f1iter.DestinationBackupVaultRef != nil {
				ko.Spec.Rules[f0idx].CopyActions[f1idx].DestinationBackupVaultARN = nil
			}
		}
	}

	for f0idx, f0iter := range ko.Spec.Rules {
		if f0iter.TargetBackupVaultRef != nil {
			ko.Spec.Rules[f0idx].TargetBackupVaultName = nil
		}
	}

	for f0idx, f0iter := range ko.Spec.Rules {
		if f0iter.TargetLogicallyAirGappedBackupVaultRef != nil {
			ko.Spec.Rules[f0idx].TargetLogicallyAirGappedBackupVaultARN = nil
		}
	}

	for f0idx, f0iter := range ko.Spec.ScanSettings {
		if f0iter.ScannerRoleRef != nil {
			ko.Spec.ScanSettings[f0idx].ScannerRoleARN = nil
		}
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForRules_CopyActions_DestinationBackupVaultARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForRules_TargetBackupVaultName(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForRules_TargetLogicallyAirGappedBackupVaultARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForScanSettings_ScannerRoleARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.BackupPlan) error {

	for _, f0iter := range ko.Spec.Rules {
		for _, f1iter := range f0iter.CopyActions {
			if f1iter.DestinationBackupVaultRef != nil && f1iter.DestinationBackupVaultARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("Rules.CopyActions.DestinationBackupVaultARN", "Rules.CopyActions.DestinationBackupVaultRef")
			}
		}
	}

	for _, f0iter := range ko.Spec.Rules {
		if f0iter.TargetBackupVaultRef != nil && f0iter.TargetBackupVaultName != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("Rules.TargetBackupVaultName", "Rules.TargetBackupVaultRef")
		}
	}

	for _, f0iter := range ko.Spec.Rules {
		if f0iter.TargetLogicallyAirGappedBackupVaultRef != nil && f0iter.TargetLogicallyAirGappedBackupVaultARN != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("Rules.TargetLogicallyAirGappedBackupVaultARN", "Rules.TargetLogicallyAirGappedBackupVaultRef")
		}
	}

	for _, f0iter := range ko.Spec.ScanSettings {
		if f0iter.ScannerRoleRef != nil && f0iter.ScannerRoleARN != nil {
			return ackerr.ResourceReferenceAndIDNotSupportedFor("ScanSettings.ScannerRoleARN", "ScanSettings.ScannerRoleRef")
		}
	}
	return nil
}

// resolveReferenceForRules_CopyActions_DestinationBackupVaultARN reads the resource referenced
// from Rules.CopyActions.DestinationBackupVaultRef field and sets the Rules.CopyActions.DestinationBackupVaultARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForRules_CopyActions_DestinationBackupVaultARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.BackupPlan,
) (hasReferences bool, err error) {
	for f0idx, f0iter := range ko.Spec.Rules {
		for f1idx, f1iter := range f0iter.CopyActions {
			if f1iter.DestinationBackupVaultRef != nil && f1iter.DestinationBackupVaultRef.From != nil {
				hasReferences = true
				arr := f1iter.DestinationBackupVaultRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Rules.CopyActions.DestinationBackupVaultRef")
				}
				namespace, err := ackrt.ResolveCrossNamespaceReference(
					ctx,
					rm.cfg.EnableCrossNamespace,
					&ko.Status.Conditions,
					ackrt.CrossNamespaceRefKindResource,
					ko.ObjectMeta.GetNamespace(),
					arr.Namespace,
					*arr.Name,
				)
				if err != nil {
					return hasReferences, err
				}
				obj := &svcapitypes.BackupVault{}
				if err := getReferencedResourceState_BackupVault(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.Rules[f0idx].CopyActions[f1idx].DestinationBackupVaultARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_BackupVault looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_BackupVault(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.BackupVault,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"BackupVault",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"BackupVault",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"BackupVault",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"BackupVault",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForRules_TargetBackupVaultName reads the resource referenced
// from Rules.TargetBackupVaultRef field and sets the Rules.TargetBackupVaultName
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForRules_TargetBackupVaultName(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.BackupPlan,
) (hasReferences bool, err error) {
	for f0idx, f0iter := range ko.Spec.Rules {
		if f0iter.TargetBackupVaultRef != nil && f0iter.TargetBackupVaultRef.From != nil {
			hasReferences = true
			arr := f0iter.TargetBackupVaultRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Rules.TargetBackupVaultRef")
			}
			namespace, err := ackrt.ResolveCrossNamespaceReference(
				ctx,
				rm.cfg.EnableCrossNamespace,
				&ko.Status.Conditions,
				ackrt.CrossNamespaceRefKindResource,
				ko.ObjectMeta.GetNamespace(),
				arr.Namespace,
				*arr.Name,
			)
			if err != nil {
				return hasReferences, err
			}
			obj := &svcapitypes.BackupVault{}
			if err := getReferencedResourceState_BackupVault(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.Rules[f0idx].TargetBackupVaultName = (*string)(obj.Spec.Name)
		}
	}

	return hasReferences, nil
}

// resolveReferenceForRules_TargetLogicallyAirGappedBackupVaultARN reads the resource referenced
// from Rules.TargetLogicallyAirGappedBackupVaultRef field and sets the Rules.TargetLogicallyAirGappedBackupVaultARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForRules_TargetLogicallyAirGappedBackupVaultARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.BackupPlan,
) (hasReferences bool, err error) {
	for f0idx, f0iter := range ko.Spec.Rules {
		if f0iter.TargetLogicallyAirGappedBackupVaultRef != nil && f0iter.TargetLogicallyAirGappedBackupVaultRef.From != nil {
			hasReferences = true
			arr := f0iter.TargetLogicallyAirGappedBackupVaultRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: Rules.TargetLogicallyAirGappedBackupVaultRef")
			}
			namespace, err := ackrt.ResolveCrossNamespaceReference(
				ctx,
				rm.cfg.EnableCrossNamespace,
				&ko.Status.Conditions,
				ackrt.CrossNamespaceRefKindResource,
				ko.ObjectMeta.GetNamespace(),
				arr.Namespace,
				*arr.Name,
			)
			if err != nil {
				return hasReferences, err
			}
			obj := &svcapitypes.BackupVault{}
			if err := getReferencedResourceState_BackupVault(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.Rules[f0idx].TargetLogicallyAirGappedBackupVaultARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
		}
	}

	return hasReferences, nil
}

// resolveReferenceForScanSettings_ScannerRoleARN reads the resource referenced
// from ScanSettings.ScannerRoleRef field and sets the ScanSettings.ScannerRoleARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForScanSettings_ScannerRoleARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.BackupPlan,
) (hasReferences bool, err error) {
	for f0idx, f0iter := range ko.Spec.ScanSettings {
		if f0iter.ScannerRoleRef != nil && f0iter.ScannerRoleRef.From != nil {
			hasReferences = true
			arr := f0iter.ScannerRoleRef.From
			if arr.Name == nil || *arr.Name == "" {
				return hasReferences, fmt.Errorf("provided resource reference is nil or empty: ScanSettings.ScannerRoleRef")
			}
			namespace, err := ackrt.ResolveCrossNamespaceReference(
				ctx,
				rm.cfg.EnableCrossNamespace,
				&ko.Status.Conditions,
				ackrt.CrossNamespaceRefKindResource,
				ko.ObjectMeta.GetNamespace(),
				arr.Namespace,
				*arr.Name,
			)
			if err != nil {
				return hasReferences, err
			}
			obj := &iamapitypes.Role{}
			if err := getReferencedResourceState_Role(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return hasReferences, err
			}
			ko.Spec.ScanSettings[f0idx].ScannerRoleARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Role looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Role(
	ctx context.Context,
	apiReader client.Reader,
	obj *iamapitypes.Role,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Role",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Role",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Role",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Role",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}
