// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_plan

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/backup"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/backup/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/backup-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.BackupPlan{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetBackupPlanOutput
	resp, err = rm.sdkapi.GetBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetBackupPlan", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) {
			switch awsErr.ErrorCode() {
			case "UNKNOWN", "ResourceNotFoundException":
				return nil, ackerr.NotFound
			}
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.AdvancedBackupSettings != nil {
		f0 := []*svcapitypes.AdvancedBackupSetting{}
		for _, f0iter := range resp.AdvancedBackupSettings {
			f0elem := &svcapitypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.StringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, f0elem)
		}
		ko.Status.AdvancedBackupSettings = f0
	} else {
		ko.Status.AdvancedBackupSettings = nil
	}
	if resp.BackupPlan != nil {
		f1 := &svcapitypes.PlanInput{}
		if resp.BackupPlan.AdvancedBackupSettings != nil {
			f1f0 := []*svcapitypes.AdvancedBackupSetting{}
			for _, f1f0iter := range resp.BackupPlan.AdvancedBackupSettings {
				f1f0elem := &svcapitypes.AdvancedBackupSetting{}
				if f1f0iter.BackupOptions != nil {
					f1f0elem.BackupOptions = aws.StringMap(f1f0iter.BackupOptions)
				}
				if f1f0iter.ResourceType != nil {
					f1f0elem.ResourceType = f1f0iter.ResourceType
				}
				f1f0 = append(f1f0, f1f0elem)
			}
			f1.AdvancedBackupSettings = f1f0
		}
		if resp.BackupPlan.BackupPlanName != nil {
			f1.BackupPlanName = resp.BackupPlan.BackupPlanName
		}
		if resp.BackupPlan.Rules != nil {
			f1f2 := []*svcapitypes.RuleInput{}
			for _, f1f2iter := range resp.BackupPlan.Rules {
				f1f2elem := &svcapitypes.RuleInput{}
				if f1f2iter.CompletionWindowMinutes != nil {
					f1f2elem.CompletionWindowMinutes = f1f2iter.CompletionWindowMinutes
				}
				if f1f2iter.CopyActions != nil {
					f1f2elemf1 := []*svcapitypes.CopyAction{}
					for _, f1f2elemf1iter := range f1f2iter.CopyActions {
						f1f2elemf1elem := &svcapitypes.CopyAction{}
						if f1f2elemf1iter.DestinationBackupVaultArn != nil {
							f1f2elemf1elem.DestinationBackupVaultARN = f1f2elemf1iter.DestinationBackupVaultArn
						}
						if f1f2elemf1iter.Lifecycle != nil {
							f1f2elemf1elemf1 := &svcapitypes.Lifecycle{}
							if f1f2elemf1iter.Lifecycle.DeleteAfterDays != nil {
								f1f2elemf1elemf1.DeleteAfterDays = f1f2elemf1iter.Lifecycle.DeleteAfterDays
							}
							if f1f2elemf1iter.Lifecycle.DeleteAfterEvent != "" {
								f1f2elemf1elemf1.DeleteAfterEvent = aws.String(string(f1f2elemf1iter.Lifecycle.DeleteAfterEvent))
							}
							if f1f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays != nil {
								f1f2elemf1elemf1.MoveToColdStorageAfterDays = f1f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays
							}
							if f1f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
								f1f2elemf1elemf1.OptInToArchiveForSupportedResources = f1f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources
							}
							f1f2elemf1elem.Lifecycle = f1f2elemf1elemf1
						}
						f1f2elemf1 = append(f1f2elemf1, f1f2elemf1elem)
					}
					f1f2elem.CopyActions = f1f2elemf1
				}
				if f1f2iter.EnableContinuousBackup != nil {
					f1f2elem.EnableContinuousBackup = f1f2iter.EnableContinuousBackup
				}
				if f1f2iter.IndexActions != nil {
					f1f2elemf3 := []*svcapitypes.IndexAction{}
					for _, f1f2elemf3iter := range f1f2iter.IndexActions {
						f1f2elemf3elem := &svcapitypes.IndexAction{}
						if f1f2elemf3iter.ResourceTypes != nil {
							f1f2elemf3elem.ResourceTypes = aws.StringSlice(f1f2elemf3iter.ResourceTypes)
						}
						f1f2elemf3 = append(f1f2elemf3, f1f2elemf3elem)
					}
					f1f2elem.IndexActions = f1f2elemf3
				}
				if f1f2iter.Lifecycle != nil {
					f1f2elemf4 := &svcapitypes.Lifecycle{}
					if f1f2iter.Lifecycle.DeleteAfterDays != nil {
						f1f2elemf4.DeleteAfterDays = f1f2iter.Lifecycle.DeleteAfterDays
					}
					if f1f2iter.Lifecycle.DeleteAfterEvent != "" {
						f1f2elemf4.DeleteAfterEvent = aws.String(string(f1f2iter.Lifecycle.DeleteAfterEvent))
					}
					if f1f2iter.Lifecycle.MoveToColdStorageAfterDays != nil {
						f1f2elemf4.MoveToColdStorageAfterDays = f1f2iter.Lifecycle.MoveToColdStorageAfterDays
					}
					if f1f2iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
						f1f2elemf4.OptInToArchiveForSupportedResources = f1f2iter.Lifecycle.OptInToArchiveForSupportedResources
					}
					f1f2elem.Lifecycle = f1f2elemf4
				}
				if f1f2iter.RecoveryPointTags != nil {
					f1f2elem.RecoveryPointTags = aws.StringMap(f1f2iter.RecoveryPointTags)
				}
				if f1f2iter.RuleName != nil {
					f1f2elem.RuleName = f1f2iter.RuleName
				}
				if f1f2iter.ScanActions != nil {
					f1f2elemf8 := []*svcapitypes.ScanAction{}
					for _, f1f2elemf8iter := range f1f2iter.ScanActions {
						f1f2elemf8elem := &svcapitypes.ScanAction{}
						if f1f2elemf8iter.MalwareScanner != "" {
							f1f2elemf8elem.MalwareScanner = aws.String(string(f1f2elemf8iter.MalwareScanner))
						}
						if f1f2elemf8iter.ScanMode != "" {
							f1f2elemf8elem.ScanMode = aws.String(string(f1f2elemf8iter.ScanMode))
						}
						f1f2elemf8 = append(f1f2elemf8, f1f2elemf8elem)
					}
					f1f2elem.ScanActions = f1f2elemf8
				}
				if f1f2iter.ScheduleExpression != nil {
					f1f2elem.ScheduleExpression = f1f2iter.ScheduleExpression
				}
				if f1f2iter.ScheduleExpressionTimezone != nil {
					f1f2elem.ScheduleExpressionTimezone = f1f2iter.ScheduleExpressionTimezone
				}
				if f1f2iter.StartWindowMinutes != nil {
					f1f2elem.StartWindowMinutes = f1f2iter.StartWindowMinutes
				}
				if f1f2iter.TargetBackupVaultName != nil {
					f1f2elem.TargetBackupVaultName = f1f2iter.TargetBackupVaultName
				}
				if f1f2iter.TargetLogicallyAirGappedBackupVaultArn != nil {
					f1f2elem.TargetLogicallyAirGappedBackupVaultARN = f1f2iter.TargetLogicallyAirGappedBackupVaultArn
				}
				f1f2 = append(f1f2, f1f2elem)
			}
			f1.Rules = f1f2
		}
		if resp.BackupPlan.ScanSettings != nil {
			f1f3 := []*svcapitypes.ScanSetting{}
			for _, f1f3iter := range resp.BackupPlan.ScanSettings {
				f1f3elem := &svcapitypes.ScanSetting{}
				if f1f3iter.MalwareScanner != "" {
					f1f3elem.MalwareScanner = aws.String(string(f1f3iter.MalwareScanner))
				}
				if f1f3iter.ResourceTypes != nil {
					f1f3elem.ResourceTypes = aws.StringSlice(f1f3iter.ResourceTypes)
				}
				if f1f3iter.ScannerRoleArn != nil {
					f1f3elem.ScannerRoleARN = f1f3iter.ScannerRoleArn
				}
				f1f3 = append(f1f3, f1f3elem)
			}
			f1.ScanSettings = f1f3
		}
		ko.Spec.BackupPlan = f1
	} else {
		ko.Spec.BackupPlan = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupPlanArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupPlanArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupPlanId != nil {
		ko.Status.BackupPlanID = resp.BackupPlanId
	} else {
		ko.Status.BackupPlanID = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	} else {
		ko.Status.VersionID = nil
	}

	rm.setStatusDefaults(ko)
	// Sync versionID from get response.
	// This is a read-only status field that reflects the current version of the backup plan.
	// Each update to a backup plan creates a new version.
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	}

	// Sync creationDate from get response.
	// This is a read-only status field that reflects when the backup plan was created.
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{Time: *resp.CreationDate}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.BackupPlanID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetBackupPlanInput, error) {
	res := &svcsdk.GetBackupPlanInput{}

	if r.ko.Status.BackupPlanID != nil {
		res.BackupPlanId = r.ko.Status.BackupPlanID
	}
	if r.ko.Status.VersionID != nil {
		res.VersionId = r.ko.Status.VersionID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateBackupPlanOutput
	_ = resp
	resp, err = rm.sdkapi.CreateBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateBackupPlan", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AdvancedBackupSettings != nil {
		f0 := []*svcapitypes.AdvancedBackupSetting{}
		for _, f0iter := range resp.AdvancedBackupSettings {
			f0elem := &svcapitypes.AdvancedBackupSetting{}
			if f0iter.BackupOptions != nil {
				f0elem.BackupOptions = aws.StringMap(f0iter.BackupOptions)
			}
			if f0iter.ResourceType != nil {
				f0elem.ResourceType = f0iter.ResourceType
			}
			f0 = append(f0, f0elem)
		}
		ko.Status.AdvancedBackupSettings = f0
	} else {
		ko.Status.AdvancedBackupSettings = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupPlanArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupPlanArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.BackupPlanId != nil {
		ko.Status.BackupPlanID = resp.BackupPlanId
	} else {
		ko.Status.BackupPlanID = nil
	}
	if resp.CreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.CreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	} else {
		ko.Status.VersionID = nil
	}

	rm.setStatusDefaults(ko)
	// Extract the BackupPlanId from the create response and set it in the status.
	// The CreateBackupPlan API returns the unique identifier for the backup plan.
	if resp.BackupPlanId != nil {
		ko.Status.BackupPlanID = resp.BackupPlanId
	}

	// Extract the VersionId from the create response and set it in the status.
	// Each update to a backup plan creates a new version, and this tracks the current version.
	if resp.VersionId != nil {
		ko.Status.VersionID = resp.VersionId
	}

	// Extract the BackupPlanArn from the create response and set it in ACKResourceMetadata.
	// This ARN uniquely identifies the backup plan resource in AWS.
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.BackupPlanArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.BackupPlanArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	// Set the ACK.ResourceSynced condition to True since BackupPlan creation is synchronous
	// and the plan is immediately available after the API call succeeds.
	ackcondition.SetSynced(&resource{ko}, corev1.ConditionTrue, nil, nil)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateBackupPlanInput, error) {
	res := &svcsdk.CreateBackupPlanInput{}

	if r.ko.Spec.BackupPlan != nil {
		f0 := &svcsdktypes.BackupPlanInput{}
		if r.ko.Spec.BackupPlan.AdvancedBackupSettings != nil {
			f0f0 := []svcsdktypes.AdvancedBackupSetting{}
			for _, f0f0iter := range r.ko.Spec.BackupPlan.AdvancedBackupSettings {
				f0f0elem := &svcsdktypes.AdvancedBackupSetting{}
				if f0f0iter.BackupOptions != nil {
					f0f0elem.BackupOptions = aws.ToStringMap(f0f0iter.BackupOptions)
				}
				if f0f0iter.ResourceType != nil {
					f0f0elem.ResourceType = f0f0iter.ResourceType
				}
				f0f0 = append(f0f0, *f0f0elem)
			}
			f0.AdvancedBackupSettings = f0f0
		}
		if r.ko.Spec.BackupPlan.BackupPlanName != nil {
			f0.BackupPlanName = r.ko.Spec.BackupPlan.BackupPlanName
		}
		if r.ko.Spec.BackupPlan.Rules != nil {
			f0f2 := []svcsdktypes.BackupRuleInput{}
			for _, f0f2iter := range r.ko.Spec.BackupPlan.Rules {
				f0f2elem := &svcsdktypes.BackupRuleInput{}
				if f0f2iter.CompletionWindowMinutes != nil {
					f0f2elem.CompletionWindowMinutes = f0f2iter.CompletionWindowMinutes
				}
				if f0f2iter.CopyActions != nil {
					f0f2elemf1 := []svcsdktypes.CopyAction{}
					for _, f0f2elemf1iter := range f0f2iter.CopyActions {
						f0f2elemf1elem := &svcsdktypes.CopyAction{}
						if f0f2elemf1iter.DestinationBackupVaultARN != nil {
							f0f2elemf1elem.DestinationBackupVaultArn = f0f2elemf1iter.DestinationBackupVaultARN
						}
						if f0f2elemf1iter.Lifecycle != nil {
							f0f2elemf1elemf1 := &svcsdktypes.Lifecycle{}
							if f0f2elemf1iter.Lifecycle.DeleteAfterDays != nil {
								f0f2elemf1elemf1.DeleteAfterDays = f0f2elemf1iter.Lifecycle.DeleteAfterDays
							}
							if f0f2elemf1iter.Lifecycle.DeleteAfterEvent != nil {
								f0f2elemf1elemf1.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f0f2elemf1iter.Lifecycle.DeleteAfterEvent)
							}
							if f0f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays != nil {
								f0f2elemf1elemf1.MoveToColdStorageAfterDays = f0f2elemf1iter.Lifecycle.MoveToColdStorageAfterDays
							}
							if f0f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
								f0f2elemf1elemf1.OptInToArchiveForSupportedResources = f0f2elemf1iter.Lifecycle.OptInToArchiveForSupportedResources
							}
							f0f2elemf1elem.Lifecycle = f0f2elemf1elemf1
						}
						f0f2elemf1 = append(f0f2elemf1, *f0f2elemf1elem)
					}
					f0f2elem.CopyActions = f0f2elemf1
				}
				if f0f2iter.EnableContinuousBackup != nil {
					f0f2elem.EnableContinuousBackup = f0f2iter.EnableContinuousBackup
				}
				if f0f2iter.IndexActions != nil {
					f0f2elemf3 := []svcsdktypes.IndexAction{}
					for _, f0f2elemf3iter := range f0f2iter.IndexActions {
						f0f2elemf3elem := &svcsdktypes.IndexAction{}
						if f0f2elemf3iter.ResourceTypes != nil {
							f0f2elemf3elem.ResourceTypes = aws.ToStringSlice(f0f2elemf3iter.ResourceTypes)
						}
						f0f2elemf3 = append(f0f2elemf3, *f0f2elemf3elem)
					}
					f0f2elem.IndexActions = f0f2elemf3
				}
				if f0f2iter.Lifecycle != nil {
					f0f2elemf4 := &svcsdktypes.Lifecycle{}
					if f0f2iter.Lifecycle.DeleteAfterDays != nil {
						f0f2elemf4.DeleteAfterDays = f0f2iter.Lifecycle.DeleteAfterDays
					}
					if f0f2iter.Lifecycle.DeleteAfterEvent != nil {
						f0f2elemf4.DeleteAfterEvent = svcsdktypes.LifecycleDeleteAfterEvent(*f0f2iter.Lifecycle.DeleteAfterEvent)
					}
					if f0f2iter.Lifecycle.MoveToColdStorageAfterDays != nil {
						f0f2elemf4.MoveToColdStorageAfterDays = f0f2iter.Lifecycle.MoveToColdStorageAfterDays
					}
					if f0f2iter.Lifecycle.OptInToArchiveForSupportedResources != nil {
						f0f2elemf4.OptInToArchiveForSupportedResources = f0f2iter.Lifecycle.OptInToArchiveForSupportedResources
					}
					f0f2elem.Lifecycle = f0f2elemf4
				}
				if f0f2iter.RecoveryPointTags != nil {
					f0f2elem.RecoveryPointTags = aws.ToStringMap(f0f2iter.RecoveryPointTags)
				}
				if f0f2iter.RuleName != nil {
					f0f2elem.RuleName = f0f2iter.RuleName
				}
				if f0f2iter.ScanActions != nil {
					f0f2elemf7 := []svcsdktypes.ScanAction{}
					for _, f0f2elemf7iter := range f0f2iter.ScanActions {
						f0f2elemf7elem := &svcsdktypes.ScanAction{}
						if f0f2elemf7iter.MalwareScanner != nil {
							f0f2elemf7elem.MalwareScanner = svcsdktypes.MalwareScanner(*f0f2elemf7iter.MalwareScanner)
						}
						if f0f2elemf7iter.ScanMode != nil {
							f0f2elemf7elem.ScanMode = svcsdktypes.ScanMode(*f0f2elemf7iter.ScanMode)
						}
						f0f2elemf7 = append(f0f2elemf7, *f0f2elemf7elem)
					}
					f0f2elem.ScanActions = f0f2elemf7
				}
				if f0f2iter.ScheduleExpression != nil {
					f0f2elem.ScheduleExpression = f0f2iter.ScheduleExpression
				}
				if f0f2iter.ScheduleExpressionTimezone != nil {
					f0f2elem.ScheduleExpressionTimezone = f0f2iter.ScheduleExpressionTimezone
				}
				if f0f2iter.StartWindowMinutes != nil {
					f0f2elem.StartWindowMinutes = f0f2iter.StartWindowMinutes
				}
				if f0f2iter.TargetBackupVaultName != nil {
					f0f2elem.TargetBackupVaultName = f0f2iter.TargetBackupVaultName
				}
				if f0f2iter.TargetLogicallyAirGappedBackupVaultARN != nil {
					f0f2elem.TargetLogicallyAirGappedBackupVaultArn = f0f2iter.TargetLogicallyAirGappedBackupVaultARN
				}
				f0f2 = append(f0f2, *f0f2elem)
			}
			f0.Rules = f0f2
		}
		if r.ko.Spec.BackupPlan.ScanSettings != nil {
			f0f3 := []svcsdktypes.ScanSetting{}
			for _, f0f3iter := range r.ko.Spec.BackupPlan.ScanSettings {
				f0f3elem := &svcsdktypes.ScanSetting{}
				if f0f3iter.MalwareScanner != nil {
					f0f3elem.MalwareScanner = svcsdktypes.MalwareScanner(*f0f3iter.MalwareScanner)
				}
				if f0f3iter.ResourceTypes != nil {
					f0f3elem.ResourceTypes = aws.ToStringSlice(f0f3iter.ResourceTypes)
				}
				if f0f3iter.ScannerRoleARN != nil {
					f0f3elem.ScannerRoleArn = f0f3iter.ScannerRoleARN
				}
				f0f3 = append(f0f3, *f0f3elem)
			}
			f0.ScanSettings = f0f3
		}
		res.BackupPlan = f0
	}
	if r.ko.Spec.BackupPlanTags != nil {
		res.BackupPlanTags = aws.ToStringMap(r.ko.Spec.BackupPlanTags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateBackupPlan(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteBackupPlanOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteBackupPlan(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteBackupPlan", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteBackupPlanInput, error) {
	res := &svcsdk.DeleteBackupPlanInput{}

	if r.ko.Status.BackupPlanID != nil {
		res.BackupPlanId = r.ko.Status.BackupPlanID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.BackupPlan,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterValueException",
		"AlreadyExistsException",
		"LimitExceededException",
		"AccessDeniedException":
		return true
	default:
		return false
	}
}
