// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package backup_selection

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID) {
		delta.Add("Spec.BackupPlanID", a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID)
	} else if a.ko.Spec.BackupPlanID != nil && b.ko.Spec.BackupPlanID != nil {
		if *a.ko.Spec.BackupPlanID != *b.ko.Spec.BackupPlanID {
			delta.Add("Spec.BackupPlanID", a.ko.Spec.BackupPlanID, b.ko.Spec.BackupPlanID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BackupSelection, b.ko.Spec.BackupSelection) {
		delta.Add("Spec.BackupSelection", a.ko.Spec.BackupSelection, b.ko.Spec.BackupSelection)
	} else if a.ko.Spec.BackupSelection != nil && b.ko.Spec.BackupSelection != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.BackupSelection.Conditions, b.ko.Spec.BackupSelection.Conditions) {
			delta.Add("Spec.BackupSelection.Conditions", a.ko.Spec.BackupSelection.Conditions, b.ko.Spec.BackupSelection.Conditions)
		} else if a.ko.Spec.BackupSelection.Conditions != nil && b.ko.Spec.BackupSelection.Conditions != nil {
			if len(a.ko.Spec.BackupSelection.Conditions.StringEquals) != len(b.ko.Spec.BackupSelection.Conditions.StringEquals) {
				delta.Add("Spec.BackupSelection.Conditions.StringEquals", a.ko.Spec.BackupSelection.Conditions.StringEquals, b.ko.Spec.BackupSelection.Conditions.StringEquals)
			} else if len(a.ko.Spec.BackupSelection.Conditions.StringEquals) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupSelection.Conditions.StringEquals, b.ko.Spec.BackupSelection.Conditions.StringEquals) {
					delta.Add("Spec.BackupSelection.Conditions.StringEquals", a.ko.Spec.BackupSelection.Conditions.StringEquals, b.ko.Spec.BackupSelection.Conditions.StringEquals)
				}
			}
			if len(a.ko.Spec.BackupSelection.Conditions.StringLike) != len(b.ko.Spec.BackupSelection.Conditions.StringLike) {
				delta.Add("Spec.BackupSelection.Conditions.StringLike", a.ko.Spec.BackupSelection.Conditions.StringLike, b.ko.Spec.BackupSelection.Conditions.StringLike)
			} else if len(a.ko.Spec.BackupSelection.Conditions.StringLike) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupSelection.Conditions.StringLike, b.ko.Spec.BackupSelection.Conditions.StringLike) {
					delta.Add("Spec.BackupSelection.Conditions.StringLike", a.ko.Spec.BackupSelection.Conditions.StringLike, b.ko.Spec.BackupSelection.Conditions.StringLike)
				}
			}
			if len(a.ko.Spec.BackupSelection.Conditions.StringNotEquals) != len(b.ko.Spec.BackupSelection.Conditions.StringNotEquals) {
				delta.Add("Spec.BackupSelection.Conditions.StringNotEquals", a.ko.Spec.BackupSelection.Conditions.StringNotEquals, b.ko.Spec.BackupSelection.Conditions.StringNotEquals)
			} else if len(a.ko.Spec.BackupSelection.Conditions.StringNotEquals) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupSelection.Conditions.StringNotEquals, b.ko.Spec.BackupSelection.Conditions.StringNotEquals) {
					delta.Add("Spec.BackupSelection.Conditions.StringNotEquals", a.ko.Spec.BackupSelection.Conditions.StringNotEquals, b.ko.Spec.BackupSelection.Conditions.StringNotEquals)
				}
			}
			if len(a.ko.Spec.BackupSelection.Conditions.StringNotLike) != len(b.ko.Spec.BackupSelection.Conditions.StringNotLike) {
				delta.Add("Spec.BackupSelection.Conditions.StringNotLike", a.ko.Spec.BackupSelection.Conditions.StringNotLike, b.ko.Spec.BackupSelection.Conditions.StringNotLike)
			} else if len(a.ko.Spec.BackupSelection.Conditions.StringNotLike) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupSelection.Conditions.StringNotLike, b.ko.Spec.BackupSelection.Conditions.StringNotLike) {
					delta.Add("Spec.BackupSelection.Conditions.StringNotLike", a.ko.Spec.BackupSelection.Conditions.StringNotLike, b.ko.Spec.BackupSelection.Conditions.StringNotLike)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BackupSelection.IAMRoleARN, b.ko.Spec.BackupSelection.IAMRoleARN) {
			delta.Add("Spec.BackupSelection.IAMRoleARN", a.ko.Spec.BackupSelection.IAMRoleARN, b.ko.Spec.BackupSelection.IAMRoleARN)
		} else if a.ko.Spec.BackupSelection.IAMRoleARN != nil && b.ko.Spec.BackupSelection.IAMRoleARN != nil {
			if *a.ko.Spec.BackupSelection.IAMRoleARN != *b.ko.Spec.BackupSelection.IAMRoleARN {
				delta.Add("Spec.BackupSelection.IAMRoleARN", a.ko.Spec.BackupSelection.IAMRoleARN, b.ko.Spec.BackupSelection.IAMRoleARN)
			}
		}
		if len(a.ko.Spec.BackupSelection.ListOfTags) != len(b.ko.Spec.BackupSelection.ListOfTags) {
			delta.Add("Spec.BackupSelection.ListOfTags", a.ko.Spec.BackupSelection.ListOfTags, b.ko.Spec.BackupSelection.ListOfTags)
		} else if len(a.ko.Spec.BackupSelection.ListOfTags) > 0 {
			if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BackupSelection.ListOfTags, b.ko.Spec.BackupSelection.ListOfTags) {
				delta.Add("Spec.BackupSelection.ListOfTags", a.ko.Spec.BackupSelection.ListOfTags, b.ko.Spec.BackupSelection.ListOfTags)
			}
		}
		if len(a.ko.Spec.BackupSelection.NotResources) != len(b.ko.Spec.BackupSelection.NotResources) {
			delta.Add("Spec.BackupSelection.NotResources", a.ko.Spec.BackupSelection.NotResources, b.ko.Spec.BackupSelection.NotResources)
		} else if len(a.ko.Spec.BackupSelection.NotResources) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.BackupSelection.NotResources, b.ko.Spec.BackupSelection.NotResources) {
				delta.Add("Spec.BackupSelection.NotResources", a.ko.Spec.BackupSelection.NotResources, b.ko.Spec.BackupSelection.NotResources)
			}
		}
		if len(a.ko.Spec.BackupSelection.Resources) != len(b.ko.Spec.BackupSelection.Resources) {
			delta.Add("Spec.BackupSelection.Resources", a.ko.Spec.BackupSelection.Resources, b.ko.Spec.BackupSelection.Resources)
		} else if len(a.ko.Spec.BackupSelection.Resources) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.BackupSelection.Resources, b.ko.Spec.BackupSelection.Resources) {
				delta.Add("Spec.BackupSelection.Resources", a.ko.Spec.BackupSelection.Resources, b.ko.Spec.BackupSelection.Resources)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.BackupSelection.SelectionName, b.ko.Spec.BackupSelection.SelectionName) {
			delta.Add("Spec.BackupSelection.SelectionName", a.ko.Spec.BackupSelection.SelectionName, b.ko.Spec.BackupSelection.SelectionName)
		} else if a.ko.Spec.BackupSelection.SelectionName != nil && b.ko.Spec.BackupSelection.SelectionName != nil {
			if *a.ko.Spec.BackupSelection.SelectionName != *b.ko.Spec.BackupSelection.SelectionName {
				delta.Add("Spec.BackupSelection.SelectionName", a.ko.Spec.BackupSelection.SelectionName, b.ko.Spec.BackupSelection.SelectionName)
			}
		}
	}

	return delta
}
