// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupPlanSpec defines the desired state of BackupPlan.
type BackupPlanSpec struct {

	// The body of a backup plan. Includes a BackupPlanName and one or more sets
	// of Rules.
	// +kubebuilder:validation:Required
	BackupPlan *PlanInput `json:"backupPlan"`
	// The tags to assign to the backup plan.
	BackupPlanTags map[string]*string `json:"backupPlanTags,omitempty"`
}

// BackupPlanStatus defines the observed state of BackupPlan
type BackupPlanStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The settings for a resource type. This option is only available for Windows
	// Volume Shadow Copy Service (VSS) backup jobs.
	// +kubebuilder:validation:Optional
	AdvancedBackupSettings []*AdvancedBackupSetting `json:"advancedBackupSettings,omitempty"`
	// The ID of the backup plan.
	// +kubebuilder:validation:Optional
	BackupPlanID *string `json:"backupPlanID,omitempty"`
	// The date and time that a backup plan is created, in Unix format and Coordinated
	// Universal Time (UTC). The value of CreationDate is accurate to milliseconds.
	// For example, the value 1516925490.087 represents Friday, January 26, 2018
	// 12:11:30.087 AM.
	// +kubebuilder:validation:Optional
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	// Unique, randomly generated, Unicode, UTF-8 encoded strings that are at most
	// 1,024 bytes long. They cannot be edited.
	// +kubebuilder:validation:Optional
	VersionID *string `json:"versionID,omitempty"`
}

// BackupPlan is the Schema for the BackupPlans API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ARN",type=string,priority=0,JSONPath=`.status.ackResourceMetadata.arn`
// +kubebuilder:printcolumn:name="PLAN-ID",type=string,priority=0,JSONPath=`.status.backupPlanID`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
type BackupPlan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              BackupPlanSpec   `json:"spec,omitempty"`
	Status            BackupPlanStatus `json:"status,omitempty"`
}

// BackupPlanList contains a list of BackupPlan
// +kubebuilder:object:root=true
type BackupPlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BackupPlan `json:"items"`
}

func init() {
	SchemeBuilder.Register(&BackupPlan{}, &BackupPlanList{})
}
