// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
)

// NotificationsSpec defines the desired state of Notifications.
type NotificationsSpec struct {

	// The name of a logical container where backups are stored. Backup vaults are
	// identified by names that are unique to the account used to create them and
	// the Amazon Web Services Region where they are created.
	//
	// Regex Pattern: `^[a-zA-Z0-9\-\_]{2,50}$`
	// +kubebuilder:validation:Required
	BackupVaultName *string `json:"-"`
	// An array of events that indicate the status of jobs to back up resources
	// to the backup vault. For the list of supported events, common use cases,
	// and code samples, see Notification options with Backup (https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-notifications.html).
	// +kubebuilder:validation:Required
	Events []*string `json:"events"`
	// The Amazon Resource Name (ARN) that specifies the topic for a backup vault’s
	// events; for example, arn:aws:sns:us-west-2:111122223333:MyVaultTopic.
	// +kubebuilder:validation:Required
	SNSTopicARN *string `json:"snsTopicARN"`
}

// NotificationsStatus defines the observed state of Notifications
type NotificationsStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// Notifications is the Schema for the Notifications API
type Notifications struct {
	Spec   NotificationsSpec   `json:"spec,omitempty"`
	Status NotificationsStatus `json:"status,omitempty"`
}
